version: '3'
services:
  node:
    build: ./node
    restart: always
    working_dir: ${PROJECT_DIR}
    user: ${CURRENT_UID}
    volumes: 
      - ${PROJECT_DIR}:/app
      - ${PROJECT_DIR}/run/node/.npm:/.npm